---
name: Bug Report
description: Report a incorrect behaviour
title: '[Bug]: '
labels: ['Type: Bug']
body:
  - type: checkboxes
    attributes:
      label: Before you continue...
      options:
        - label: I am using the latest version or commit.
          required: true
        - label: I have checked and found no similar issues.
          required: true
  - type: textarea
    attributes:
      label: Description
      description: A description of what is incorrect.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behaviour
      description: What you expected to happen.
  - type: textarea
    attributes:
      label: Extra Details
      description: Anything else that should be made aware.